### ISSUE TITLE
Beautify CSS

### ISSUE THREAD

**Issue by xPaw** [tristen/tablesort#118]
I think we can improve a couple of things in the default CSS that is provided:
1. Beautify it a little
2. Remove `::selection` and use `user-select` instead
3. Fix opacity when hovering on column header when it's been sorted
4. No need to check which direction it's sorted to display the arrow

```css
table th[role=columnheader] {
	cursor: pointer;
}

table th[role=columnheader]:after {
	content: '';
	float: right;
	margin-top: 7px;
	border-width: 0 4px 4px;
	border-style: solid;
	border-color: #404040 transparent;
	visibility: hidden;
	-webkit-user-select: none;
	-moz-user-select: none;
	user-select: none;
}

table th[aria-sort=ascending]:after {
	border-bottom: none;
	border-width: 4px 4px 0;
}

table th[aria-sort]:after {
	visibility: visible;
	opacity: 0.4;
}

table th[role=columnheader]:hover:after {
	visibility: visible;
	opacity: 1;
}
```

For simplicity, we probably should create `tablesort.css`.

**Comment by xPaw** [comment]
Also, I think users might already have `role=columnheader` on headers, but chose to also have `no-sort` class on it. We probably should account for that.

**Comment by tristen** [comment]
@xPaw these changes look great and yeah, for simplicity including a `tablesort.css` stylesheet makes sense too.

> Also, I think users might already have `role=columnheader` on headers, but chose to also have `no-sort` class on it. We probably should account for that.

> Current logic in code is to only add `role=columnheader` to headers that do not have `no-sort`, but for accessibility purposes we might need to add it to all headers. @tristen What do you think?

Yep, we should add `role=columnheader` always and add a rule in css that accounts for the addition of `no-sort` on the element. @xPaw you good to cook these changes into a PR?

**Comment by xPaw** [comment]
@tristen Should I do `:not(.no-sort)` or add a `.sortable` on theads instead?

**Comment by tristen** [comment]
@xPaw ahhh both those options aren't ideal. Does:

```css
table th[role=columnheader].no-sort:after 
table th[role=columnheader].no-sort:hover::after { visibility: hidden; }
```

Work? It's a little wonky but it avoids adding an extra class or a [not well supported](http://caniuse.com/#search=%3Anot) selector..
